[package]
name = "text_crdt_rust"
version = "0.1.0"
authors = ["Seph Gentle <me@josephg.com>"]
edition = "2018"

# I can't get this working.

#[build]
#rustflags = ["-C", "linker-flavor=lld-link"]

#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "linker-flavor=lld-link"]
#linker = "lld"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartstring = "0.2.6"
ropey = "1.1.0"
smallvec = { version = "1.6.1", features = ["union"] }
lazy_static = "1.4.0"

# Only used for printing stats. TODO: Move me to dev-dependencies!
humansize = "1.1.1"

[dev-dependencies]
criterion = "^0.3"
rand = { version = "^0.8", features = ["small_rng"] }
crdt-testdata = { path = "src/testdata" }

[profile.release]
#debug = true
lto = true
#opt-level = "s"
codegen-units = 1
#panic = 'abort'

[features]
memusage = []
inlinerope = []

[[bench]]
name = "benchmark"
harness = false