[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
#debug = true
lto = true
#opt-level = "s"
codegen-units = 1
#panic = "abort"

[profile.release.package.diamond-js]
opt-level = 3
#opt-level = "s"
#debugging = true