[package]
name = "text_crdt_rust"
version = "0.1.0"
authors = ["Seph Gentle <me@josephg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inlinable_string = "0.1.11"
#ropey = "1.1.0"
smallvec = "1.4.0"

[dev-dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
criterion = "^0.3"
rand = { version = "^0.8", features = ["small_rng"] }

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
#panic = 'abort'

[[bench]]
name = "benchmark"
harness = false