[package]
name = "rle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Put this behind a feature flag.
smallvec = "1.6"
